# Generated by Django 4.2.8 on 2023-12-09 10:54

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Post name')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('short_diskription', models.CharField(max_length=400, verbose_name='Description')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish dete')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created dete')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='PostPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_point_text', models.TextField(verbose_name='Post point')),
                ('post_images', models.ImageField(blank=True, upload_to=blog.models.save_images, verbose_name='Point imgage')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
