# Generated by Django 4.2.8 on 2024-01-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postpoint_post_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_diskription',
            new_name='short_description',
        ),
    ]
